---
# handlers file for deploy_sites
- name: Restart nginx
  systemd:
    name: nginx
    state: restarted

- name: Restart php-fpm
  systemd:
    name: php-fpm
    state: restarted

- name: Restart php7.4-fpm
  systemd:
    name: php7.4-fpm
    state: restarted

