---
# tasks file for install_nginx
- name: install nginx for RHEL
  import_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: install nginx for Debian
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

